server:
  port: 9999

eureka:
  instance:
    instance-id: ${eureka.host}:${spring.application.name}:${server.port}
    prefer-ip-address: false
    hostname: ${eureka.host}
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host}:${server.port}/eureka/

management:
  security:
    enabled: false

spring:
  application:
    name: lmtech-eureka

