data_source : 
  driver_class_name : com.mysql.jdbc.Driver
  url : jdbc:mysql://47.100.130.91:3306/connect?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  user_name : root
  password : uAiqwVwjJ8-i
  max_active : 50
  initial_size : 10
  max_idle : 500
  maxWait : 60000
  test_on_borrow : false
  test_while_idle : true
  time_between_eviction_runs_millis : 60000
  min_evictable_idle_time_millis : 300000
  num_tests_per_eviction_run : 200
  remove_abandoned : true
  remove_abandoned_timeout : 180

service :
  url_uc_getintegeral : http://172.30.2.26:8104/uic/user/findIntegralMemberUserInfo.do
  url_uc_integralsign : http://172.30.2.26:8104/uic/user/addOrRedIntegralMember.do
  url_uc_integraldetals : http://172.30.2.26:8104/uic/user/findIntegralMemberDetail.do
  url_uc_getsmscode : http://172.30.2.26:8104/uic/user/postVerificationCode.do
  url_uc_register : http://172.30.2.26:8104/uic/user/userRegisterAndBind.do
  url_uc_finduser : http://172.30.2.26:8104/uic/user/findUserInfo.do
  url_uc_get_member_ext : http://172.30.2.26:8104/uic/user/findIntegralMemberUserInfo.do
  
  url_account_checkuser : http://172.30.2.26:8126/wallet/portal/checkUser.do
  url_account_register : http://172.30.2.26:8126/wallet/portal/register.do
  url_account_mybalance : http://172.30.2.26:8126/wallet/balance/mybalance.do
  url_oa_exist_user : http://172.30.2.26:8132/third/account/verification.do
  
  url_login4wap : http://api4test.380star.com/buyer/user/otherlogin4wap.do
  url_relogini4wap : http://api4test.380star.com/buyer/user/rlogin.do
  url_buyer_refresh_settle : http://api4test.380star.com/buyer/cart/refreshsettle.do
  url_buyer_submit_order_pre : http://api4test.380star.com/buyer/order/submitpreorder.do
  url_buyer_order_list : http://api4test.380star.com/buyer/order/myorderlist.do
  url_istokenexpire : http://api4test.380star.com/buyer/user/istokenexpire.do
  
  url_recharge_request : http://172.30.2.26:8101/trade/recharge/rechargereq.do
  url_recharge_payment : http://172.30.2.26:8101/trade/recharge/rechargepay.do
  url_recharge_applet_payment : http://172.30.2.26:8101/trade/recharge/rechargeAppletpay.do
  url_recharge_list : http://172.30.2.26:8101/trade/recharge/backend/rechargelist.do;
  
  url_account_balance : http://172.30.2.26:8126/wallet/balance/mybalance.do
  url_account_balance_list : http://172.30.2.26:8126/wallet/balance/recordlist.do
  url_account_recorddetail : http://172.30.2.26:8126/wallet/balance/recorddetail.do
  url_account_addwxrechargemoney : http://172.30.2.26:8126/wallet/balance/addWXRechargeMoney.do
  
  url_account_set_paypswd : http://172.30.2.26:8126/wallet/portal/setpwd.do
  url_account_change_paypswd : http://172.30.2.26:8126/wallet/portal/modifypwd.do
  url_account_reset_paypswd : http://172.30.2.26:8126/wallet/portal/resetpwd.do
  
  url_balance_checkpswd : http://172.30.2.26:8126/wallet/trade/checkpwd.do
  url_balance_lock : http://172.30.2.26:8126/wallet/trade/lock.do
  url_balance_unlock : http://172.30.2.26:8126/wallet/trade/unlock.do
  url_balance_reduce : http://172.30.2.26:8126/wallet/trade/reduce.do

  url_zero_menoy_pay : http://http://172.30.2.26:8101/trade/pay/wecat/zeroMenoyPay.do
  send_wechat_message : http://172.30.2.26:8108/api/msg/sendWechatMessage
  update_token : http://172.30.2.26:8108/api/msg/updateToken
  
wx :
  app_id : wx6ddffdd9dff8e11a
  secret : d481eba8ed01fbba68c80cb1befbddda
  card_id : pxr3zwbOADp8KRbfpFUEBlkRN0Ho
  pay_api_key : pW25hoI9tKiKf7DyAYxBsH9HxSx3LmLx
  applet_app_id : wx2c9ff9cdc7190603
  applet_secret : 59ab73eda6d548bdb948362188549aaf
  applet_card_id : pxr3zwbOADp8KRbfpFUEBlkRN0Ho
  applet_pay_api_key : pW25hoI9tKiKf7DyAYxBsH9HxSx3LmLx
  template_id : 

integral :
  lottery : 
    show_latest_prize_count : 5
    integral_pay : 1
    coefficient : 10

card :
  active :
    active_present_bonus : 100
    inner_user_present_card_count : 10
    inner_user_present_card_month : 12
    present_vpass_card_count : 10
    present_vpass_card_month : 6
  paymen :
    level_vpass_price : 99

ui :
  cardcategory :
    img_banner_url : http://cd.wewineu.com/cardh5/images/banner.jpg

swagger : 
  enable : true
  basepackage : com.ea
  headerparams : AppType

member_card : 
  vpass_wx_bg : http://mmbiz.qpic.cn/mmbiz_png/PL68icyUicl8IBG8yHLCdmMTp3hwLLgEibCXYqBOjLE8LiapyI5nKRPd0qsGOctia2niacCaakGK6SbyaThMqT1cSiamQ/0
  pass_wx_bg : http://mmbiz.qpic.cn/mmbiz_png/PL68icyUicl8IBG8yHLCdmMTp3hwLLgEibCmZticLAYKogd4rzsXibbkA3yAVTjdPbaok5qGGrySyOWuyUZqLoVicFkQ/0
  vpass_h5_bg : http://cd.wewineu.com/resource/images/card/bfb15218449ec73851b5d53eed7a8692.png
  pass_h5_bg : http://cd.wewineu.com/resource/images/card/5b317ab60c4f888bfe0598c8dceb6ec2.png
 
spring :
  redis :
    database : 0
    host : 47.100.130.91
    password : 
    port : 6379
    timeout: 5000
    pool : 
      max-idle : 8
      min-idle : 0
      max-active : 8
      max-wait : -1

lmtech :
  redis : 
    prefix : "ea_card_crm:"
    
sms :
  access_key_id : LTAIM9xljPp0X7Nd
  access_key_secret : ywAJW3OsMMfsQeHxuQouc4JbPlUp6S
  sign_name : 游物欧品
  template_code : SMS_116805052
  expire_time : 1800
  enable_sms : true
