data_source : 
  driver_class_name : com.mysql.jdbc.Driver
  url : jdbc:mysql://47.100.130.91:3306/connect?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  user_name : root
  password : uAiqwVwjJ8-i
  max_active : 50
  initial_size : 10
  max_idle : 500
  maxWait : 60000
  test_on_borrow : false
  test_while_idle : true
  time_between_eviction_runs_millis : 60000
  min_evictable_idle_time_millis : 300000
  num_tests_per_eviction_run : 200
  remove_abandoned : true
  remove_abandoned_timeout : 180

swagger : 
  enable : true
  basepackage : com.ea
  headerparams : 

spring :
  redis :
    database : 0
    host : 47.100.130.91
    password : 
    port : 6379
    timeout: 5000
    pool : 
      max-idle : 8
      min-idle : 0
      max-active : 8
      max-wait : -1

trade :
  pay_api_key : pW25hoI9tKiKf7DyAYxBsH9HxSx3LmLx
  app_id : wx6ddffdd9dff8e11a
  mch_id : 1320924401
  body : ScanPay
  spbill_create_ip : 47.100.130.91
  notify_url : http://cd.wewineu.com/trade/notify/wxPayNotify
  trade_type : JSAPI
