data_source : 
  driver_class_name : com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/connect?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  user_name : root
  password : root
  max_active : 50
  initial_size : 5
  max_idle : 80
  maxWait : 60000
  test_on_borrow : false
  test_while_idle : true
  time_between_eviction_runs_millis : 60000
  min_evictable_idle_time_millis : 300000
  num_tests_per_eviction_run : 200
  remove_abandoned : true
  remove_abandoned_timeout : 180

redis :
  ip : localhost
  port : 6379
  auth :

swagger : 
  enable : true
  basepackage : com.lmtech
  headerparams : 