data_source : 
  driver_class_name : com.mysql.jdbc.Driver
  url : jdbc:mysql://47.100.130.91:3306/connect?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  user_name : root
  password : uAiqwVwjJ8-i
  max_active : 50
  initial_size : 10
  max_idle : 500
  maxWait : 60000
  test_on_borrow : false
  test_while_idle : true
  time_between_eviction_runs_millis : 60000
  min_evictable_idle_time_millis : 300000
  num_tests_per_eviction_run : 200
  remove_abandoned : true
  remove_abandoned_timeout : 180

swagger : 
  ui : 
    enable : true
    basepackage : com.lmtech
    headerparams : 

spring :
  redis :
    database : 0
    host : 47.100.130.91
    password : 
    port : 6379
    timeout: 5000
    pool : 
      max-idle : 8
      min-idle : 0
      max-active : 8
      max-wait : -1

lmtech :
  redis : 
    prefix : "ea_card_crm:"